<?xml version="1.0" encoding="UTF-8"?>
<testng-results retried="1" ignored="1" total="6" passed="3" failed="1" skipped="0">
  <reporter-output>
  </reporter-output>
  <suite started-at="2025-03-03T13:21:18 IST" name="Suite" finished-at="2025-03-03T13:22:29 IST" duration-ms="71025">
    <groups>
      <group name="ErrorHandling">
        <method signature="ErrorValidation.loginErrorValidation()[pri:0, instance:Seleniumlearning.Manasaproject.ErrorValidation@4d0d9fe7]" name="loginErrorValidation" class="Seleniumlearning.Manasaproject.ErrorValidation"/>
      </group> <!-- ErrorHandling -->
      <group name="Purchase">
        <method signature="ProjectTestNG.submitOrder(java.lang.String,java.lang.String,java.lang.String)[pri:0, instance:Seleniumlearning.Manasaproject.ProjectTestNG@53045c6c]" name="submitOrder" class="Seleniumlearning.Manasaproject.ProjectTestNG"/>
      </group> <!-- Purchase -->
    </groups>
    <test started-at="2025-03-03T13:21:18 IST" name="ProjectTestNG" finished-at="2025-03-03T13:21:56 IST" duration-ms="37573">
      <class name="Seleniumlearning.Manasaproject.ProjectTestNG">
        <test-method is-config="true" signature="launchApplication()[pri:0, instance:Seleniumlearning.Manasaproject.ProjectTestNG@53045c6c]" started-at="2025-03-03T13:21:18 IST" name="launchApplication" finished-at="2025-03-03T13:21:27 IST" duration-ms="9216" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- launchApplication -->
        <test-method signature="submitOrder(java.lang.String,java.lang.String,java.lang.String)[pri:0, instance:Seleniumlearning.Manasaproject.ProjectTestNG@53045c6c]" started-at="2025-03-03T13:21:27 IST" name="submitOrder" data-provider="getData" finished-at="2025-03-03T13:21:39 IST" duration-ms="11662" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[rahulshettyacademy]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[learning]]>
              </value>
            </param>
            <param index="2">
              <value>
                <![CDATA[Blackberry]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- submitOrder -->
        <test-method is-config="true" signature="tearDown()[pri:0, instance:Seleniumlearning.Manasaproject.ProjectTestNG@53045c6c]" started-at="2025-03-03T13:21:39 IST" name="tearDown" finished-at="2025-03-03T13:21:39 IST" duration-ms="229" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
        <test-method is-config="true" signature="launchApplication()[pri:0, instance:Seleniumlearning.Manasaproject.ProjectTestNG@53045c6c]" started-at="2025-03-03T13:21:39 IST" name="launchApplication" finished-at="2025-03-03T13:21:43 IST" duration-ms="3960" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- launchApplication -->
        <test-method signature="submitOrder(java.lang.String,java.lang.String,java.lang.String)[pri:0, instance:Seleniumlearning.Manasaproject.ProjectTestNG@53045c6c]" started-at="2025-03-03T13:21:43 IST" name="submitOrder" data-provider="getData" finished-at="2025-03-03T13:21:55 IST" duration-ms="11800" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[rahulshettyacademy]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[learning]]>
              </value>
            </param>
            <param index="2">
              <value>
                <![CDATA[iphone X]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- submitOrder -->
        <test-method is-config="true" signature="tearDown()[pri:0, instance:Seleniumlearning.Manasaproject.ProjectTestNG@53045c6c]" started-at="2025-03-03T13:21:55 IST" name="tearDown" finished-at="2025-03-03T13:21:56 IST" duration-ms="522" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
      </class> <!-- Seleniumlearning.Manasaproject.ProjectTestNG -->
    </test> <!-- ProjectTestNG -->
    <test started-at="2025-03-03T13:21:57 IST" name="ErrorValidation" finished-at="2025-03-03T13:22:29 IST" duration-ms="32187">
      <class name="Seleniumlearning.Manasaproject.ErrorValidation">
        <test-method is-config="true" signature="launchApplication()[pri:0, instance:Seleniumlearning.Manasaproject.ErrorValidation@4d0d9fe7]" started-at="2025-03-03T13:21:57 IST" name="launchApplication" finished-at="2025-03-03T13:22:01 IST" duration-ms="3718" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- launchApplication -->
        <test-method signature="ProductErrorValidation()[pri:0, instance:Seleniumlearning.Manasaproject.ErrorValidation@4d0d9fe7]" started-at="2025-03-03T13:22:01 IST" name="ProductErrorValidation" finished-at="2025-03-03T13:22:11 IST" duration-ms="10596" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- ProductErrorValidation -->
        <test-method is-config="true" signature="tearDown()[pri:0, instance:Seleniumlearning.Manasaproject.ErrorValidation@4d0d9fe7]" started-at="2025-03-03T13:22:11 IST" name="tearDown" finished-at="2025-03-03T13:22:12 IST" duration-ms="394" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
        <test-method is-config="true" signature="launchApplication()[pri:0, instance:Seleniumlearning.Manasaproject.ErrorValidation@4d0d9fe7]" started-at="2025-03-03T13:22:12 IST" name="launchApplication" finished-at="2025-03-03T13:22:16 IST" duration-ms="4339" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- launchApplication -->
        <test-method retried="true" signature="loginErrorValidation()[pri:0, instance:Seleniumlearning.Manasaproject.ErrorValidation@4d0d9fe7]" started-at="2025-03-03T13:22:16 IST" name="loginErrorValidation" finished-at="2025-03-03T13:22:20 IST" duration-ms="4090" status="SKIP">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [Incorrect username/password.] but found [Incorrect usernam/password.]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [Incorrect username/password.] but found [Incorrect usernam/password.]
at org.testng.Assert.fail(Assert.java:111)
at org.testng.Assert.failNotEquals(Assert.java:1578)
at org.testng.Assert.assertEqualsImpl(Assert.java:150)
at org.testng.Assert.assertEquals(Assert.java:132)
at org.testng.Assert.assertEquals(Assert.java:656)
at org.testng.Assert.assertEquals(Assert.java:666)
at Seleniumlearning.Manasaproject.ErrorValidation.loginErrorValidation(ErrorValidation.java:33)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
at java.base/java.lang.reflect.Method.invoke(Method.java:580)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:141)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:686)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:230)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:63)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:992)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:203)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:154)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:134)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
at org.testng.TestRunner.privateRun(TestRunner.java:739)
at org.testng.TestRunner.run(TestRunner.java:614)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:421)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:413)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:373)
at org.testng.SuiteRunner.run(SuiteRunner.java:312)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1274)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1208)
at org.testng.TestNG.runSuites(TestNG.java:1112)
at org.testng.TestNG.run(TestNG.java:1079)
at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:283)
at org.apache.maven.surefire.testng.TestNGXmlTestSuite.execute(TestNGXmlTestSuite.java:75)
at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:120)
at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:377)
at org.apache.maven.surefire.booter.ForkedBooter.execute(ForkedBooter.java:138)
at org.apache.maven.surefire.booter.ForkedBooter.run(ForkedBooter.java:465)
at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:451)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- loginErrorValidation -->
        <test-method is-config="true" signature="tearDown()[pri:0, instance:Seleniumlearning.Manasaproject.ErrorValidation@4d0d9fe7]" started-at="2025-03-03T13:22:20 IST" name="tearDown" finished-at="2025-03-03T13:22:20 IST" duration-ms="201" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
        <test-method is-config="true" signature="launchApplication()[pri:0, instance:Seleniumlearning.Manasaproject.ErrorValidation@4d0d9fe7]" started-at="2025-03-03T13:22:20 IST" name="launchApplication" finished-at="2025-03-03T13:22:23 IST" duration-ms="3058" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- launchApplication -->
        <test-method signature="loginErrorValidation()[pri:0, instance:Seleniumlearning.Manasaproject.ErrorValidation@4d0d9fe7]" started-at="2025-03-03T13:22:23 IST" name="loginErrorValidation" finished-at="2025-03-03T13:22:28 IST" duration-ms="4315" status="FAIL">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [Incorrect username/password.] but found [Incorrect usernam/password.]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [Incorrect username/password.] but found [Incorrect usernam/password.]
at org.testng.Assert.fail(Assert.java:111)
at org.testng.Assert.failNotEquals(Assert.java:1578)
at org.testng.Assert.assertEqualsImpl(Assert.java:150)
at org.testng.Assert.assertEquals(Assert.java:132)
at org.testng.Assert.assertEquals(Assert.java:656)
at org.testng.Assert.assertEquals(Assert.java:666)
at Seleniumlearning.Manasaproject.ErrorValidation.loginErrorValidation(ErrorValidation.java:33)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
at java.base/java.lang.reflect.Method.invoke(Method.java:580)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:141)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:686)
at org.testng.internal.invokers.TestInvoker.retryFailed(TestInvoker.java:269)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:76)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:992)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:203)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:154)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:134)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
at org.testng.TestRunner.privateRun(TestRunner.java:739)
at org.testng.TestRunner.run(TestRunner.java:614)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:421)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:413)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:373)
at org.testng.SuiteRunner.run(SuiteRunner.java:312)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1274)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1208)
at org.testng.TestNG.runSuites(TestNG.java:1112)
at org.testng.TestNG.run(TestNG.java:1079)
at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:283)
at org.apache.maven.surefire.testng.TestNGXmlTestSuite.execute(TestNGXmlTestSuite.java:75)
at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:120)
at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:377)
at org.apache.maven.surefire.booter.ForkedBooter.execute(ForkedBooter.java:138)
at org.apache.maven.surefire.booter.ForkedBooter.run(ForkedBooter.java:465)
at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:451)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- loginErrorValidation -->
        <test-method is-config="true" signature="tearDown()[pri:0, instance:Seleniumlearning.Manasaproject.ErrorValidation@4d0d9fe7]" started-at="2025-03-03T13:22:29 IST" name="tearDown" finished-at="2025-03-03T13:22:29 IST" duration-ms="156" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
      </class> <!-- Seleniumlearning.Manasaproject.ErrorValidation -->
    </test> <!-- ErrorValidation -->
  </suite> <!-- Suite -->
</testng-results>
